/** §7.7 / §20 — companion and antagonist pairings (order-independent). */

import type { CompanionRelationship } from "../types/models";

export const companions: CompanionRelationship[] = [
  {
    aPlantId: "tomato",
    bPlantId: "basil",
    type: "beneficial",
    reason: "repels thrips and hornworm moths; classic flavor pairing",
    strength: "strong",
  },
  {
    aPlantId: "tomato",
    bPlantId: "carrot",
    type: "beneficial",
    reason: "loosened soil and light canopy shade coexist well",
    strength: "weak",
  },
  {
    aPlantId: "tomato",
    bPlantId: "broccoli",
    type: "antagonistic",
    reason: "heavy feeders compete; brassicas can stunt tomato growth",
    strength: "moderate",
  },
  {
    aPlantId: "tomato",
    bPlantId: "kale",
    type: "antagonistic",
    reason: "heavy feeders compete; brassicas can stunt tomato growth",
    strength: "moderate",
  },
  {
    aPlantId: "pepper_sweet",
    bPlantId: "basil",
    type: "beneficial",
    reason: "deters aphids and spider mites near peppers",
    strength: "moderate",
  },
  {
    aPlantId: "bush_bean",
    bPlantId: "onion_bulb",
    type: "antagonistic",
    reason: "alliums inhibit legume growth and nitrogen fixation",
    strength: "moderate",
  },
  {
    aPlantId: "snap_pea",
    bPlantId: "onion_bulb",
    type: "antagonistic",
    reason: "alliums inhibit legume growth and nitrogen fixation",
    strength: "moderate",
  },
  {
    aPlantId: "snap_pea",
    bPlantId: "carrot",
    type: "beneficial",
    reason: "peas fix nitrogen; roots occupy different depths",
    strength: "moderate",
  },
  {
    aPlantId: "snap_pea",
    bPlantId: "radish",
    type: "beneficial",
    reason: "radish breaks soil crust and marks slow rows",
    strength: "weak",
  },
  {
    aPlantId: "snap_pea",
    bPlantId: "spinach",
    type: "beneficial",
    reason: "pea trellis shades spinach, delaying bolt; spinach mulches roots",
    strength: "moderate",
  },
  {
    aPlantId: "carrot",
    bPlantId: "onion_bulb",
    type: "beneficial",
    reason: "allium scent confuses carrot rust fly",
    strength: "moderate",
  },
  {
    aPlantId: "carrot",
    bPlantId: "radish",
    type: "beneficial",
    reason: "radish germinates fast, breaking crust for slow carrot seed",
    strength: "weak",
  },
  {
    aPlantId: "lettuce_leaf",
    bPlantId: "radish",
    type: "beneficial",
    reason: "quick interplant; lettuce shades soil, radish is gone before crowding",
    strength: "weak",
  },
  {
    aPlantId: "lettuce_leaf",
    bPlantId: "carrot",
    type: "beneficial",
    reason: "shallow lettuce roots don't compete with deep carrot roots",
    strength: "weak",
  },
  {
    aPlantId: "cucumber",
    bPlantId: "bush_bean",
    type: "beneficial",
    reason: "beans fix nitrogen for the hungry vine",
    strength: "moderate",
  },
  {
    aPlantId: "cucumber",
    bPlantId: "radish",
    type: "beneficial",
    reason: "radish is said to deter cucumber beetles",
    strength: "weak",
  },
  {
    aPlantId: "zucchini",
    bPlantId: "bush_bean",
    type: "beneficial",
    reason: "beans fix nitrogen for the heavy-feeding squash",
    strength: "weak",
  },
  {
    aPlantId: "broccoli",
    bPlantId: "onion_bulb",
    type: "beneficial",
    reason: "allium scent deters cabbage pests",
    strength: "moderate",
  },
  {
    aPlantId: "kale",
    bPlantId: "onion_bulb",
    type: "beneficial",
    reason: "allium scent deters cabbage pests",
    strength: "moderate",
  },
  {
    aPlantId: "broccoli",
    bPlantId: "lettuce_leaf",
    type: "beneficial",
    reason: "lettuce living-mulches the soil between slow brassicas",
    strength: "weak",
  },
  {
    aPlantId: "beet",
    bPlantId: "onion_bulb",
    type: "beneficial",
    reason: "compatible feeders; alliums deter leaf-miner flies somewhat",
    strength: "weak",
  },
  {
    aPlantId: "beet",
    bPlantId: "kale",
    type: "beneficial",
    reason: "different root depths and nutrient draws",
    strength: "weak",
  },
  {
    aPlantId: "tomato",
    bPlantId: "marigold",
    type: "beneficial",
    reason: "scent confuses whiteflies; roots suppress nematodes",
    strength: "moderate",
  },
  {
    aPlantId: "cucumber",
    bPlantId: "marigold",
    type: "beneficial",
    reason: "deters cucumber beetles around the vines",
    strength: "weak",
  },
  {
    aPlantId: "tomato",
    bPlantId: "potato",
    type: "antagonistic",
    reason: "share late blight; adjacency spreads it both ways",
    strength: "strong",
  },
  {
    aPlantId: "garlic",
    bPlantId: "bush_bean",
    type: "antagonistic",
    reason: "alliums inhibit legume growth and nitrogen fixation",
    strength: "moderate",
  },
  {
    aPlantId: "garlic",
    bPlantId: "snap_pea",
    type: "antagonistic",
    reason: "alliums inhibit legume growth and nitrogen fixation",
    strength: "moderate",
  },
  {
    aPlantId: "strawberry",
    bPlantId: "garlic",
    type: "beneficial",
    reason: "allium scent deters spider mites in the berry bed",
    strength: "weak",
  },
  {
    aPlantId: "carrot",
    bPlantId: "dill",
    type: "antagonistic",
    reason: "close apiaceae relatives; dill can cross and stunt carrots",
    strength: "weak",
  },
];
