/**
 * §28.2 catalog expansion, tranche 2 (Phase 5): herbs, alliums, perennials,
 * flowers, and remaining staples. Same conventions as plants.ts; the rest of
 * the §28.2 list lands in later content tranches (README backlog).
 */

import type { Plant } from "../types/models";

export const plantsExpansion: Plant[] = [
  {
    id: "pole_bean",
    commonName: "Pole Bean",
    scientificName: "Phaseolus vulgaris",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 15.5,
    gddBaseTempC: 10,
    daysToMaturity: { min: 60, max: 75, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    matureHeightCm: { min: 180, max: 300 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 10, betweenRowCm: 60, squareFootCount: 8 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 1, max: 4 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 6, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: { schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }] },
    supportStructures: ["trellis"],
    commonPests: ["mexican bean beetle", "aphid"],
    commonDiseases: ["bean rust", "anthracnose"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "0.5-1 kg",
      indicators: ["pods pencil-thick, before seeds bulge"],
      method: "two hands; pick every 2-3 days to keep vines setting",
    },
    varietalIds: [],
    recipeIds: ["recipe_garlic_green_beans"],
    difficulty: "easy",
    description: "Climbing bean: more weeks of harvest than bush types from one sowing, in exchange for a trellis.",
    iconKey: "pole_bean",
    tags: ["vining", "summer", "succession"],
  },
  {
    id: "cabbage",
    commonName: "Cabbage",
    scientificName: "Brassica oleracea var. capitata",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 1, max: 11 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 4,
    daysToMaturity: { min: 65, max: 100, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 30, max: 40 },
    soilPh: { min: 6.0, max: 7.5 },
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 45, max: 70 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: -3, max: -1 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "nitrogen side-dress", intervalDays: 21 },
      ],
    },
    supportStructures: ["row_cover"],
    commonPests: ["cabbage worm", "aphid", "slug"],
    commonDiseases: ["clubroot", "black rot"],
    harvest: {
      windowDays: { min: 7, max: 21 },
      yieldPerPlant: "1 head (1-3 kg)",
      indicators: ["head firm when squeezed"],
      method: "cut at the base; leave outer leaves for mini-heads",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description: "Cool-season heading staple; steady water prevents the heads splitting.",
    iconKey: "cabbage",
    tags: ["cool-season", "storage", "fall"],
  },
  {
    id: "swiss_chard",
    commonName: "Swiss Chard",
    scientificName: "Beta vulgaris subsp. cicla",
    familyId: "amaranthaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 4,
    daysToMaturity: { min: 50, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 5,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 25, max: 40 },
    spacing: { inRowCm: 20, betweenRowCm: 40, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "transplant", "indoor_start"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      transplantWeeksFromLastFrost: { min: 0, max: 2 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 1.2,
      germinationDays: { min: 5, max: 12 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: { schedule: [{ atStage: "planted", type: "compost-amended bed" }] },
    supportStructures: [],
    commonPests: ["leaf miner", "slug"],
    commonDiseases: ["cercospora leaf spot"],
    harvest: {
      windowDays: { min: 60, max: 150 },
      yieldPerPlant: "continuous outer stalks",
      indicators: ["stalks 25+ cm; cut-and-come-again all season"],
      method: "twist or cut outer stalks at the base",
    },
    varietalIds: [],
    recipeIds: ["recipe_sauteed_spinach"],
    difficulty: "easy",
    description: "The green that doesn't quit: shrugs off heat that bolts spinach and stands into frost.",
    iconKey: "swiss_chard",
    tags: ["easy", "shade-tolerant", "summer", "fall", "container-friendly"],
  },
  {
    id: "arugula",
    commonName: "Arugula",
    scientificName: "Eruca vesicaria",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 4,
    gddBaseTempC: 4,
    daysToMaturity: { min: 21, max: 40, from: "sow" },
    photoperiod: "long_day",
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.0 },
    matureHeightCm: { min: 15, max: 25 },
    matureSpreadCm: { min: 10, max: 20 },
    spacing: { inRowCm: 8, betweenRowCm: 25, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -4, max: 3 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 3, max: 8 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: { schedule: [{ atStage: "planted", type: "compost-amended bed" }] },
    supportStructures: [],
    commonPests: ["flea beetle"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 10, max: 21 },
      yieldPerPlant: "continuous leaves",
      indicators: ["leaves 8-12 cm; hotter flavor as it ages"],
      method: "cut-and-come-again",
    },
    varietalIds: [],
    recipeIds: ["recipe_garden_salad"],
    difficulty: "easy",
    description: "Peppery three-week salad green; the fastest thing in the catalog after radish.",
    iconKey: "arugula",
    tags: ["fast", "succession", "cool-season", "container-friendly", "shade-tolerant"],
  },
  {
    id: "cilantro",
    commonName: "Cilantro / Coriander",
    scientificName: "Coriandrum sativum",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 4,
    daysToMaturity: { min: 45, max: 70, from: "sow" },
    photoperiod: "long_day",
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.2, max: 6.8 },
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 10, max: 20 },
    spacing: { inRowCm: 10, betweenRowCm: 25, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: { schedule: [{ atStage: "vegetative", type: "half-strength balanced", intervalDays: 28 }] },
    supportStructures: [],
    commonPests: ["aphid"],
    commonDiseases: ["bacterial leaf spot"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "continuous leaves, then coriander seed",
      indicators: ["stems 15+ cm; bolts fast in heat — then let it seed"],
      method: "cut outer stems; harvest seed heads dry",
    },
    varietalIds: [],
    recipeIds: ["recipe_fresh_salsa"],
    difficulty: "easy",
    description: "Resents transplanting and bolts at the first heat — sow little and often, in part shade come summer.",
    iconKey: "cilantro",
    tags: ["fast", "succession", "cool-season", "kitchen"],
  },
  {
    id: "dill",
    commonName: "Dill",
    scientificName: "Anethum graveolens",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 4,
    daysToMaturity: { min: 40, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 5.5, max: 6.5 },
    matureHeightCm: { min: 60, max: 120 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 6 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: { schedule: [{ atStage: "planted", type: "none on rich soil" }] },
    supportStructures: [],
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 21, max: 45 },
      yieldPerPlant: "fronds, then seed heads",
      indicators: ["feathery fronds any time; seed when heads brown"],
      method: "snip fronds; bag seed heads to dry",
    },
    varietalIds: [],
    recipeIds: ["recipe_quick_pickles"],
    difficulty: "easy",
    description: "Pickle-jar essential and a swallowtail-butterfly host; self-sows happily.",
    iconKey: "dill",
    tags: ["pollinator", "kitchen", "self-sows"],
  },
  {
    id: "parsley",
    commonName: "Parsley",
    scientificName: "Petroselinum crispum",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "biennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 10,
    gddBaseTempC: 4,
    daysToMaturity: { min: 70, max: 90, from: "sow" },
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    matureHeightCm: { min: 25, max: 45 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      directSowWeeksFromLastFrost: { min: -3, max: 2 },
      transplantWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced liquid feed", intervalDays: 28 }] },
    supportStructures: [],
    commonPests: ["aphid", "parsley worm (swallowtail)"],
    commonDiseases: ["crown rot"],
    harvest: {
      windowDays: { min: 60, max: 180 },
      yieldPerPlant: "continuous outer stems",
      indicators: ["stems with 3+ leaf segments"],
      method: "cut outer stems at the base",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Slow to germinate (legend says it visits the devil seven times first), then generous for a full year.",
    iconKey: "parsley",
    tags: ["kitchen", "shade-tolerant", "container-friendly"],
  },
  {
    id: "thyme",
    commonName: "Thyme",
    scientificName: "Thymus vulgaris",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 5, max: 9 },
    heatTolerance: "high",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 15,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 180, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 10, max: 20 },
    soilPh: { min: 6.0, max: 8.0 },
    soilPreference: ["well-drained", "lean", "gritty"],
    matureHeightCm: { min: 15, max: 30 },
    matureSpreadCm: { min: 30, max: 40 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      transplantWeeksFromLastFrost: { min: 0, max: 3 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: { schedule: [{ atStage: "planted", type: "none — rich soil dulls the oils" }] },
    supportStructures: [],
    commonPests: ["spider mite"],
    commonDiseases: ["root rot"],
    harvest: {
      windowDays: { min: 90, max: 240 },
      yieldPerPlant: "continuous sprigs",
      indicators: ["sprigs 8+ cm, before flowering for best oil"],
      method: "shear lightly, never into bare wood",
    },
    varietalIds: [],
    recipeIds: ["recipe_honey_glazed_carrots"],
    difficulty: "easy",
    description: "Mediterranean evergreen: poor dry soil and full sun, wet winter feet are what kill it.",
    iconKey: "thyme",
    tags: ["perennial", "pollinator", "drought-tolerant", "container-friendly"],
  },
  {
    id: "mint",
    commonName: "Mint",
    scientificName: "Mentha spicata",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 4,
    daysToMaturity: { min: 60, max: 90, from: "transplant" },
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "high",
    waterMmPerWeek: { min: 30, max: 45 },
    soilPh: { min: 6.0, max: 7.5 },
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 60, max: 200 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: 0, max: 4 },
      plantingDepthCm: 0.5,
      germinationDays: { min: 10, max: 16 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: { schedule: [{ atStage: "vegetative", type: "compost top-dress", intervalDays: 60 }] },
    supportStructures: [],
    commonPests: ["aphid", "spider mite"],
    commonDiseases: ["mint rust"],
    harvest: {
      windowDays: { min: 90, max: 200 },
      yieldPerPlant: "continuous sprigs",
      indicators: ["sprigs before flowering for sweetest flavor"],
      method: "pinch tips hard and often",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Delicious thug — give it a container or it takes the bed. Tolerates wet feet and shade.",
    iconKey: "mint",
    tags: ["perennial", "container-friendly", "shade-tolerant", "spreads"],
  },
  {
    id: "garlic",
    commonName: "Garlic",
    scientificName: "Allium sativum",
    familyId: "amaryllidaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 1,
    minSoilTempC: 0,
    gddBaseTempC: 1,
    daysToMaturity: { min: 240, max: 270, from: "sow" },
    photoperiod: "long_day",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["loose", "well-drained", "rich"],
    matureHeightCm: { min: 45, max: 60 },
    matureSpreadCm: { min: 10, max: 15 },
    spacing: { inRowCm: 12, betweenRowCm: 25, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      // planted as cloves in fall: 2–6 weeks before first frost
      fallWeeksFromFirstFrost: { min: -34, max: -32 },
      directSowWeeksFromLastFrost: { min: -26, max: -24 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 40 },
    },
    stageTemplateId: "tmpl_allium_bulb",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "nitrogen side-dress in early spring", intervalDays: 28 },
      ],
    },
    supportStructures: [],
    commonPests: ["onion maggot"],
    commonDiseases: ["white rot", "rust"],
    harvest: {
      windowDays: { min: 7, max: 14 },
      yieldPerPlant: "1 bulb",
      indicators: ["lower third of leaves brown, upper still green"],
      method: "lift carefully; cure 3-4 weeks dry and airy",
    },
    varietalIds: [],
    recipeIds: ["recipe_garlic_green_beans", "recipe_caramelized_onions"],
    difficulty: "easy",
    description: "Plant cloves in fall, harvest mid-summer: the slowest, easiest crop in the garden. Hates wet winter soil.",
    iconKey: "garlic",
    tags: ["fall-planted", "storage", "long-season", "easy"],
  },
  {
    id: "potato",
    commonName: "Potato",
    scientificName: "Solanum tuberosum",
    familyId: "solanaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 10 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 7,
    daysToMaturity: { min: 70, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 5.0, max: 6.5 },
    soilPreference: ["loose", "well-drained", "slightly acid"],
    matureHeightCm: { min: 45, max: 75 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 75, squareFootCount: 1 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -3, max: 2 },
      plantingDepthCm: 10,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10, low pH" },
        { atStage: "vegetative", type: "hill soil up as stems grow", notes: "Hilling is the real feeding." },
      ],
    },
    supportStructures: ["mound"],
    commonPests: ["colorado potato beetle", "wireworm", "aphid"],
    commonDiseases: ["late blight", "scab"],
    harvest: {
      windowDays: { min: 14, max: 40 },
      yieldPerPlant: "1-2 kg",
      indicators: ["new potatoes at flowering; storage crop when tops die back"],
      method: "fork from the side, lift gently",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Plant seed pieces, hill twice, dig treasure. Shares late blight with tomatoes — keep them apart and rotate.",
    iconKey: "potato",
    tags: ["storage", "easy", "spring"],
  },
  {
    id: "strawberry",
    commonName: "Strawberry",
    scientificName: "Fragaria × ananassa",
    familyId: "rosaceae",
    category: "fruit",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 2,
    minSoilTempC: 10,
    gddBaseTempC: 4,
    daysToMaturity: { min: 90, max: 120, from: "transplant" },
    photoperiod: "short_day",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 5.5, max: 6.8 },
    soilPreference: ["well-drained", "rich", "mulched"],
    matureHeightCm: { min: 15, max: 25 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 4 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 0,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "fruiting", type: "low-N berry feed", intervalDays: 21 },
      ],
    },
    supportStructures: ["row_cover"],
    commonPests: ["slug", "spittlebug", "birds"],
    commonDiseases: ["gray mold (botrytis)", "verticillium wilt"],
    harvest: {
      windowDays: { min: 21, max: 40 },
      yieldPerPlant: "0.3-0.7 kg",
      indicators: ["fully red with no white shoulders"],
      method: "pinch the stem, not the fruit; pick ripe daily",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description: "Perennial bed-former: crown at soil level, runners managed, straw mulch under the fruit (it's in the name).",
    iconKey: "strawberry",
    tags: ["perennial", "container-friendly", "kids"],
  },
  {
    id: "sunflower",
    commonName: "Sunflower",
    scientificName: "Helianthus annuus",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 13,
    gddBaseTempC: 7,
    daysToMaturity: { min: 70, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    matureHeightCm: { min: 150, max: 350 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 30, betweenRowCm: 75, squareFootCount: 1 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 1, max: 4 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: { schedule: [{ atStage: "planted", type: "compost-amended bed" }] },
    supportStructures: ["stake"],
    commonPests: ["birds", "squirrels"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "1 head (cutting) or seed head",
      indicators: ["back of head yellows when seed is ready"],
      method: "cut heads, dry upside down for seed",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Bee magnet and bird feeder on a stem; mind the shadow it casts on the bed behind it (the sun map knows).",
    iconKey: "sunflower",
    tags: ["pollinator", "kids", "tall", "summer"],
  },
  {
    id: "marigold",
    commonName: "Marigold",
    scientificName: "Tagetes patula",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 15,
    gddBaseTempC: 10,
    daysToMaturity: { min: 50, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.5 },
    matureHeightCm: { min: 15, max: 45 },
    matureSpreadCm: { min: 15, max: 30 },
    spacing: { inRowCm: 20, betweenRowCm: 25, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 1, max: 4 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: { schedule: [{ atStage: "planted", type: "none — lean soil means more bloom" }] },
    supportStructures: [],
    commonPests: ["slug", "spider mite"],
    commonDiseases: ["botrytis"],
    harvest: {
      windowDays: { min: 60, max: 120 },
      yieldPerPlant: "continuous blooms",
      indicators: ["deadhead spent blooms to keep it flowering"],
      method: "pinch spent heads; save dried seed",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "The classic edge-of-bed companion: pest-confusing scent, nonstop bloom, ridiculously easy.",
    iconKey: "marigold",
    tags: ["pollinator", "companion", "container-friendly", "easy", "summer"],
  },
];
