/**
 * §7.3 / §28.2 — the plant catalog. Phase 0 ships these 15 fully-populated
 * records (the full §28.2 list lands in Phase 5). Values are mainstream
 * horticultural references, kept internally consistent (§30.8): week offsets
 * are relative to last spring frost (negative = before), temperatures °C,
 * lengths cm, water mm/week. Tomato and radish follow the spec's own §28.1
 * reference records. seedViabilityYears per §31.1; waterloggingSensitivity
 * per §31.2 (Mediterranean herbs / solanums / heavy-soil roots = high).
 */

import type { Plant } from "../types/models";

export const plants: Plant[] = [
  {
    id: "tomato",
    commonName: "Tomato",
    scientificName: "Solanum lycopersicum",
    familyId: "solanaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 4,
    minSoilTempC: 15.5,
    optSoilTempC: { min: 21, max: 29 },
    gddBaseTempC: 10,
    gddToMaturity: 1300,
    daysToMaturity: { min: 55, max: 90, from: "transplant" },
    photoperiod: "day_neutral",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "loamy", "rich"],
    matureHeightCm: { min: 90, max: 200 },
    matureSpreadCm: { min: 45, max: 90 },
    spacing: { inRowCm: 45, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "flowering", type: "low-N high-P/K", intervalDays: 14 },
      ],
    },
    supportStructures: ["cage", "stake", "trellis"],
    commonPests: ["hornworm", "aphid", "whitefly"],
    commonDiseases: ["early blight", "blossom end rot", "late blight"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "3-5 kg",
      indicators: ["full color", "slight give when pressed"],
      method: "twist or snip ripe fruit",
    },
    varietalIds: ["tomato_sungold", "tomato_san_marzano", "tomato_early_girl"],
    recipeIds: ["recipe_fresh_salsa", "recipe_roasted_sauce", "recipe_caprese"],
    difficulty: "moderate",
    description:
      "Warm-season fruiting crop; needs full sun, steady water, and support.",
    iconKey: "tomato",
    tags: ["container-friendly", "pollinator", "summer"],
  },
  {
    id: "pepper_sweet",
    commonName: "Sweet Pepper",
    scientificName: "Capsicum annuum",
    familyId: "solanaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 2,
    minSoilTempC: 18,
    optSoilTempC: { min: 24, max: 30 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 60, max: 90, from: "transplant" },
    photoperiod: "day_neutral",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -9, max: -7 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 5-10-10" },
        { atStage: "fruiting", type: "low-N high-K", intervalDays: 21 },
      ],
    },
    supportStructures: ["stake", "cage"],
    commonPests: ["aphid", "flea beetle", "spider mite"],
    commonDiseases: ["bacterial leaf spot", "blossom end rot"],
    harvest: {
      windowDays: { min: 21, max: 50 },
      yieldPerPlant: "5-10 fruits",
      indicators: ["full size, thick walls", "color change for ripe sweetness"],
      method: "snip with short stem",
    },
    varietalIds: ["pepper_california_wonder", "pepper_banana"],
    recipeIds: ["recipe_fresh_salsa", "recipe_spring_stir_fry"],
    difficulty: "moderate",
    description:
      "Heat-loving, slow-starting fruiting crop; resents cold feet and dries badly in wind.",
    iconKey: "pepper_sweet",
    tags: ["container-friendly", "summer"],
  },
  {
    id: "cucumber",
    commonName: "Cucumber",
    scientificName: "Cucumis sativus",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 5,
    minSoilTempC: 15.5,
    optSoilTempC: { min: 21, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 50, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 25, max: 50 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "warm"],
    matureHeightCm: { min: 150, max: 200 },
    matureSpreadCm: { min: 30, max: 90 },
    spacing: { inRowCm: 30, betweenRowCm: 90, squareFootCount: 2 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 3 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2,
      germinationDays: { min: 3, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 14 },
      ],
    },
    supportStructures: ["trellis"],
    commonPests: ["cucumber beetle", "aphid", "spider mite"],
    commonDiseases: ["powdery mildew", "bacterial wilt", "downy mildew"],
    harvest: {
      windowDays: { min: 21, max: 60 },
      yieldPerPlant: "10-20 fruits",
      indicators: ["firm, uniformly green, before yellowing"],
      method: "snip — pulling tears the vine",
    },
    varietalIds: ["cucumber_marketmore", "cucumber_lemon"],
    recipeIds: ["recipe_quick_pickles", "recipe_garden_salad"],
    difficulty: "easy",
    description:
      "Fast warm-season vine; trellising keeps fruit straight and mildew down.",
    iconKey: "cucumber",
    tags: ["fast", "container-friendly", "summer", "vining"],
  },
  {
    id: "zucchini",
    commonName: "Zucchini",
    scientificName: "Cucurbita pepo",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 5,
    minSoilTempC: 15.5,
    optSoilTempC: { min: 21, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 45, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 25, max: 50 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["rich", "well-drained"],
    matureHeightCm: { min: 60, max: 90 },
    matureSpreadCm: { min: 90, max: 120 },
    spacing: { inRowCm: 60, betweenRowCm: 120 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 3 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "fruiting", type: "balanced liquid feed", intervalDays: 14 },
      ],
    },
    supportStructures: ["mound"],
    commonPests: ["squash bug", "squash vine borer", "cucumber beetle"],
    commonDiseases: ["powdery mildew", "blossom end rot"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "6-10 kg",
      indicators: ["15-20 cm long, glossy skin"],
      method: "cut stem with a knife; check every other day",
    },
    varietalIds: ["zucchini_black_beauty"],
    recipeIds: ["recipe_zucchini_fritters"],
    difficulty: "easy",
    description:
      "Famously productive bush squash; two plants feed a household.",
    iconKey: "zucchini",
    tags: ["fast", "prolific", "summer"],
  },
  {
    id: "bush_bean",
    commonName: "Bush Bean",
    scientificName: "Phaseolus vulgaris",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 15.5,
    optSoilTempC: { min: 21, max: 27 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 50, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "average"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 8, betweenRowCm: 45, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 1, max: 4 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 6, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [
        {
          atStage: "planted",
          type: "none — fixes its own nitrogen",
          notes: "Excess N grows leaves, not pods.",
        },
      ],
    },
    supportStructures: [],
    commonPests: ["mexican bean beetle", "aphid", "slug"],
    commonDiseases: ["bean rust", "bacterial blight"],
    harvest: {
      windowDays: { min: 14, max: 28 },
      yieldPerPlant: "0.2-0.4 kg",
      indicators: ["pods pencil-thick, snap cleanly, seeds not bulging"],
      method: "two hands — hold the stem, pull the pod",
    },
    varietalIds: ["bean_provider", "bean_royal_burgundy"],
    recipeIds: ["recipe_garlic_green_beans"],
    difficulty: "easy",
    description:
      "No-fuss nitrogen fixer; sow every 2-3 weeks for a steady supply.",
    iconKey: "bush_bean",
    tags: ["fast", "succession", "easy", "summer"],
  },
  {
    id: "snap_pea",
    commonName: "Snap Pea",
    scientificName: "Pisum sativum",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 4.5,
    optSoilTempC: { min: 10, max: 21 },
    gddBaseTempC: 4,
    daysToMaturity: { min: 58, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "cool"],
    matureHeightCm: { min: 120, max: 180 },
    matureSpreadCm: { min: 10, max: 20 },
    spacing: { inRowCm: 5, betweenRowCm: 45, squareFootCount: 8 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -6, max: -2 },
      fallWeeksFromFirstFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [
        {
          atStage: "planted",
          type: "none — fixes its own nitrogen",
          notes: "Inoculant helps in new beds.",
        },
      ],
    },
    supportStructures: ["trellis"],
    commonPests: ["aphid", "pea weevil", "slug"],
    commonDiseases: ["powdery mildew", "root rot"],
    harvest: {
      windowDays: { min: 14, max: 28 },
      yieldPerPlant: "0.2-0.5 kg",
      indicators: ["pods plump and glossy, snap crisply"],
      method: "two hands; pick daily once flowing",
    },
    varietalIds: ["pea_sugar_snap", "pea_cascadia"],
    recipeIds: ["recipe_spring_stir_fry"],
    difficulty: "easy",
    description:
      "Cool-season climber that shrugs off frost; first crop in, first out.",
    iconKey: "snap_pea",
    tags: ["cool-season", "vining", "spring", "fall"],
  },
  {
    id: "broccoli",
    commonName: "Broccoli",
    scientificName: "Brassica oleracea var. italica",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    optSoilTempC: { min: 15, max: 24 },
    gddBaseTempC: 4,
    daysToMaturity: { min: 55, max: 80, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["rich", "moisture-retentive"],
    matureHeightCm: { min: 45, max: 75 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -7, max: -5 },
      transplantWeeksFromLastFrost: { min: -2, max: 0 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "nitrogen side-dress", intervalDays: 21 },
      ],
    },
    supportStructures: ["row_cover"],
    commonPests: ["cabbage worm", "aphid", "flea beetle"],
    commonDiseases: ["clubroot", "black rot"],
    harvest: {
      windowDays: { min: 7, max: 21 },
      yieldPerPlant: "1 head + side shoots",
      indicators: ["head tight, buds closed, before any yellow shows"],
      method: "cut at a slant; side shoots follow for weeks",
    },
    varietalIds: ["broccoli_calabrese", "broccoli_belstar"],
    recipeIds: ["recipe_roasted_broccoli", "recipe_spring_stir_fry"],
    difficulty: "moderate",
    description:
      "Cool-season heading brassica; spring and fall crops, hates heat at heading.",
    iconKey: "broccoli",
    tags: ["cool-season", "spring", "fall"],
  },
  {
    id: "kale",
    commonName: "Kale",
    scientificName: "Brassica oleracea var. sabellica",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    optSoilTempC: { min: 10, max: 24 },
    gddBaseTempC: 4,
    daysToMaturity: { min: 50, max: 65, from: "sow" },
    sun: "full",
    sunHoursMin: 5,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["rich", "well-drained"],
    matureHeightCm: { min: 30, max: 90 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -7, max: -5 },
      directSowWeeksFromLastFrost: { min: -5, max: -3 },
      transplantWeeksFromLastFrost: { min: -3, max: -1 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 1.2,
      germinationDays: { min: 4, max: 9 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "nitrogen side-dress", intervalDays: 28 },
      ],
    },
    supportStructures: ["row_cover"],
    commonPests: ["cabbage worm", "aphid", "flea beetle"],
    commonDiseases: ["clubroot", "downy mildew"],
    harvest: {
      windowDays: { min: 30, max: 90 },
      yieldPerPlant: "continuous outer leaves",
      indicators: ["leaves hand-sized; sweeter after frost"],
      method: "snap outer leaves down; leave the crown",
    },
    varietalIds: ["kale_lacinato", "kale_red_russian"],
    recipeIds: ["recipe_kale_chips", "recipe_garden_salad"],
    difficulty: "easy",
    description:
      "Tough cut-and-come-again green; frost sweetens it and it stands all winter in mild zones.",
    iconKey: "kale",
    tags: ["cool-season", "shade-tolerant", "fall", "easy"],
  },
  {
    id: "carrot",
    commonName: "Carrot",
    scientificName: "Daucus carota",
    familyId: "apiaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 7,
    optSoilTempC: { min: 13, max: 24 },
    gddBaseTempC: 5,
    daysToMaturity: { min: 60, max: 80, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["deep", "loose", "stone-free", "sandy"],
    matureHeightCm: { min: 20, max: 30 },
    matureSpreadCm: { min: 5, max: 8 },
    spacing: { inRowCm: 4, betweenRowCm: 30, squareFootCount: 16 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -3, max: 3 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 6, max: 21 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        {
          atStage: "planted",
          type: "low-N, no fresh manure",
          notes: "Fresh manure forks the roots.",
        },
      ],
    },
    supportStructures: ["row_cover"],
    commonPests: ["carrot rust fly", "wireworm"],
    commonDiseases: ["alternaria leaf blight", "cavity spot"],
    harvest: {
      windowDays: { min: 14, max: 40 },
      yieldPerPlant: "1 root",
      indicators: ["shoulders 2 cm across at the soil line"],
      method: "loosen with a fork, then pull",
    },
    varietalIds: ["carrot_nantes", "carrot_danvers", "carrot_rainbow"],
    recipeIds: [
      "recipe_honey_glazed_carrots",
      "recipe_garden_salad",
      "recipe_spring_stir_fry",
    ],
    difficulty: "moderate",
    description:
      "Slow to germinate, fussy about soil texture, worth every bit of it.",
    iconKey: "carrot",
    tags: ["cool-season", "succession", "storage"],
  },
  {
    id: "radish",
    commonName: "Radish",
    scientificName: "Raphanus sativus",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 22, max: 30, from: "sow" },
    photoperiod: "long_day",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.0 },
    matureHeightCm: { min: 10, max: 20 },
    matureSpreadCm: { min: 5, max: 8 },
    spacing: { inRowCm: 3, betweenRowCm: 15, squareFootCount: 16 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -4, max: 4 },
      fallWeeksFromFirstFrost: { min: 4, max: 6 },
      plantingDepthCm: 1.2,
      germinationDays: { min: 3, max: 7 },
    },
    stageTemplateId: "tmpl_root_fast",
    fertilization: {
      schedule: [{ atStage: "planted", type: "compost-amended bed" }],
    },
    supportStructures: [],
    commonPests: ["flea beetle", "root maggot"],
    commonDiseases: ["clubroot"],
    harvest: {
      windowDays: { min: 5, max: 10 },
      yieldPerPlant: "1 root",
      indicators: ["shoulders ~2-3 cm at soil line"],
      method: "pull",
    },
    varietalIds: ["radish_cherry_belle", "radish_french_breakfast"],
    recipeIds: ["recipe_quick_pickled_radish", "recipe_garden_salad"],
    difficulty: "easy",
    description:
      "Fast cool-season root; ideal for succession sowing and intercropping.",
    iconKey: "radish",
    tags: ["fast", "container-friendly", "succession", "cool-season"],
  },
  {
    id: "beet",
    commonName: "Beet",
    scientificName: "Beta vulgaris",
    familyId: "amaranthaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    optSoilTempC: { min: 10, max: 26 },
    gddBaseTempC: 5,
    daysToMaturity: { min: 50, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 5,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["loose", "well-drained", "boron-adequate"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 10, max: 15 },
    spacing: { inRowCm: 8, betweenRowCm: 30, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -4, max: 4 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 1.2,
      germinationDays: { min: 5, max: 12 },
    },
    stageTemplateId: "tmpl_root_fast",
    fertilization: {
      schedule: [{ atStage: "planted", type: "compost-amended bed" }],
    },
    supportStructures: [],
    commonPests: ["leaf miner", "flea beetle"],
    commonDiseases: ["cercospora leaf spot", "scab"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "1 root + greens",
      indicators: ["roots 4-7 cm across; greens usable any time"],
      method: "pull; twist (don't cut) tops to limit bleeding",
    },
    varietalIds: ["beet_detroit_dark_red", "beet_chioggia"],
    recipeIds: ["recipe_roasted_beets"],
    difficulty: "easy",
    description:
      "Two crops in one — earthy roots and chard-like greens; each 'seed' is a cluster, so thin early.",
    iconKey: "beet",
    tags: ["cool-season", "succession", "storage"],
  },
  {
    id: "onion_bulb",
    commonName: "Bulb Onion",
    scientificName: "Allium cepa",
    familyId: "amaryllidaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 3, max: 10 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    optSoilTempC: { min: 13, max: 24 },
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 110, from: "transplant" },
    photoperiod: "long_day",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["loose", "well-drained", "weed-free"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 8, max: 12 },
    spacing: { inRowCm: 10, betweenRowCm: 30, squareFootCount: 9 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      transplantWeeksFromLastFrost: { min: -4, max: -2 },
      plantingDepthCm: 1.2,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_allium_bulb",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "nitrogen side-dress", intervalDays: 21 },
      ],
    },
    supportStructures: [],
    commonPests: ["onion maggot", "thrips"],
    commonDiseases: ["downy mildew", "white rot"],
    harvest: {
      windowDays: { min: 7, max: 21 },
      yieldPerPlant: "1 bulb",
      indicators: ["tops yellow and flop over"],
      method: "lift, cure 2-3 weeks dry before storing",
    },
    varietalIds: ["onion_walla_walla", "onion_red_baron"],
    recipeIds: [
      "recipe_caramelized_onions",
      "recipe_fresh_salsa",
      "recipe_roasted_sauce",
    ],
    difficulty: "moderate",
    description:
      "Day-length driven bulber — match the variety to your latitude; weed early, it never out-competes anything.",
    iconKey: "onion_bulb",
    tags: ["storage", "long-season"],
  },
  {
    id: "lettuce_leaf",
    commonName: "Leaf Lettuce",
    scientificName: "Lactuca sativa",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 4,
    optSoilTempC: { min: 10, max: 21 },
    gddBaseTempC: 4,
    daysToMaturity: { min: 30, max: 50, from: "sow" },
    photoperiod: "long_day",
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["moisture-retentive", "rich"],
    matureHeightCm: { min: 15, max: 25 },
    matureSpreadCm: { min: 15, max: 25 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: -4, max: 2 },
      transplantWeeksFromLastFrost: { min: -2, max: 0 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 2, max: 10 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "half-strength nitrogen", intervalDays: 14 },
      ],
    },
    supportStructures: ["row_cover"],
    commonPests: ["slug", "aphid"],
    commonDiseases: ["downy mildew", "bottom rot"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "continuous outer leaves",
      indicators: ["leaves 10-15 cm; bitter sap means bolting has begun"],
      method: "cut-and-come-again, 2-3 cm above the crown",
    },
    varietalIds: ["lettuce_black_seeded_simpson", "lettuce_oakleaf"],
    recipeIds: ["recipe_garden_salad"],
    difficulty: "easy",
    description:
      "The classic quick salad green; heat makes it bitter and tall — shade and succession are the cure.",
    iconKey: "lettuce_leaf",
    tags: ["fast", "succession", "shade-tolerant", "container-friendly", "cool-season"],
  },
  {
    id: "spinach",
    commonName: "Spinach",
    scientificName: "Spinacia oleracea",
    familyId: "amaranthaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 4,
    optSoilTempC: { min: 7, max: 18 },
    gddBaseTempC: 4,
    daysToMaturity: { min: 35, max: 50, from: "sow" },
    photoperiod: "long_day",
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.5, max: 7.5 },
    soilPreference: ["rich", "moisture-retentive"],
    matureHeightCm: { min: 15, max: 30 },
    matureSpreadCm: { min: 15, max: 25 },
    spacing: { inRowCm: 8, betweenRowCm: 30, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -6, max: -2 },
      fallWeeksFromFirstFrost: { min: 2, max: 4 },
      plantingDepthCm: 1.2,
      germinationDays: { min: 5, max: 14 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "nitrogen side-dress", intervalDays: 21 },
      ],
    },
    supportStructures: ["row_cover"],
    commonPests: ["leaf miner", "slug", "aphid"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "continuous outer leaves",
      indicators: ["leaves palm-sized; harvest hard at the first sign of a seed stalk"],
      method: "pinch outer leaves or cut the whole rosette",
    },
    varietalIds: ["spinach_bloomsdale", "spinach_space"],
    recipeIds: ["recipe_sauteed_spinach", "recipe_garden_salad"],
    difficulty: "easy",
    description:
      "The hardiest salad green — sows in cold mud, bolts the moment days turn long and warm.",
    iconKey: "spinach",
    tags: ["cool-season", "fast", "shade-tolerant", "spring", "fall"],
  },
  {
    id: "basil",
    commonName: "Basil",
    scientificName: "Ocimum basilicum",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    optSoilTempC: { min: 21, max: 29 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 30, max: 60, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "warm"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 25, max: 40 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["indoor_start", "transplant", "direct_sow"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 2, max: 4 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: {
      schedule: [
        {
          atStage: "vegetative",
          type: "half-strength balanced feed",
          intervalDays: 28,
          notes: "Overfeeding dulls the aroma.",
        },
      ],
    },
    supportStructures: [],
    commonPests: ["aphid", "slug", "japanese beetle"],
    commonDiseases: ["downy mildew", "fusarium wilt"],
    harvest: {
      windowDays: { min: 30, max: 90 },
      yieldPerPlant: "continuous tips",
      indicators: ["stems 6+ leaf pairs; pinch above a pair"],
      method: "pinch tips weekly; never strip single leaves",
    },
    varietalIds: ["basil_genovese", "basil_thai"],
    recipeIds: ["recipe_pesto", "recipe_caprese", "recipe_roasted_sauce"],
    difficulty: "easy",
    description:
      "Heat-loving kitchen staple; cold nights below 10°C blacken it, so never rush it out.",
    iconKey: "basil",
    tags: ["container-friendly", "pollinator", "summer", "kitchen"],
  },
];
