/** §7.5 / §18 — recipes linked back to catalog plants. */

import type { Recipe } from "../types/models";

export const recipes: Recipe[] = [
  {
    id: "recipe_fresh_salsa",
    title: "Fresh Garden Salsa",
    plantIds: ["tomato", "pepper_sweet", "onion_bulb"],
    servings: 4,
    prepMinutes: 15,
    ingredients: [
      { item: "ripe tomatoes, diced", quantity: 4, plantId: "tomato" },
      { item: "sweet pepper, minced", quantity: 1, plantId: "pepper_sweet" },
      { item: "onion, finely diced", quantity: 0.5, plantId: "onion_bulb" },
      { item: "lime, juiced", quantity: 1 },
      { item: "salt", quantity: 0.5, unit: "tsp" },
      { item: "cilantro, chopped", quantity: 0.25, unit: "cup" },
    ],
    steps: [
      "Dice tomatoes and drain excess juice for 5 minutes.",
      "Combine with pepper, onion, lime juice, and salt.",
      "Rest 15 minutes; fold in cilantro just before serving.",
    ],
    usesStage: "harvest",
    tags: ["quick", "raw", "summer"],
  },
  {
    id: "recipe_roasted_sauce",
    title: "Roasted Tomato Sauce",
    plantIds: ["tomato", "basil", "onion_bulb"],
    servings: 6,
    prepMinutes: 15,
    cookMinutes: 60,
    ingredients: [
      { item: "paste tomatoes, halved", quantity: 2, unit: "kg", plantId: "tomato" },
      { item: "onion, quartered", quantity: 1, plantId: "onion_bulb" },
      { item: "garlic cloves", quantity: 6 },
      { item: "olive oil", quantity: 3, unit: "tbsp" },
      { item: "basil leaves", quantity: 1, unit: "cup", plantId: "basil" },
    ],
    steps: [
      "Roast tomatoes, onion, and garlic with oil at 200°C for 45 minutes.",
      "Blend with basil; simmer 15 minutes to thicken.",
      "Freeze or can in batches.",
    ],
    usesStage: "harvest",
    tags: ["preserving", "batch-cook"],
  },
  {
    id: "recipe_caprese",
    title: "Caprese Salad",
    plantIds: ["tomato", "basil"],
    servings: 2,
    prepMinutes: 10,
    ingredients: [
      { item: "ripe tomatoes, sliced", quantity: 2, plantId: "tomato" },
      { item: "fresh mozzarella, sliced", quantity: 125, unit: "g" },
      { item: "basil leaves", quantity: 12, plantId: "basil" },
      { item: "olive oil and flaky salt", quantity: 1 },
    ],
    steps: [
      "Layer tomato, mozzarella, and basil.",
      "Dress with oil and salt at the table.",
    ],
    usesStage: "harvest",
    tags: ["quick", "raw", "vegetarian"],
  },
  {
    id: "recipe_quick_pickles",
    title: "Refrigerator Pickles",
    plantIds: ["cucumber"],
    servings: 8,
    prepMinutes: 20,
    ingredients: [
      { item: "cucumbers, sliced", quantity: 4, plantId: "cucumber" },
      { item: "vinegar", quantity: 1, unit: "cup" },
      { item: "water", quantity: 1, unit: "cup" },
      { item: "salt", quantity: 1, unit: "tbsp" },
      { item: "sugar", quantity: 1, unit: "tbsp" },
      { item: "dill and garlic", quantity: 1 },
    ],
    steps: [
      "Pack cucumber slices into jars with dill and garlic.",
      "Heat brine to dissolve salt and sugar; pour over.",
      "Refrigerate 24 hours; keeps 3 weeks.",
    ],
    usesStage: "harvest",
    tags: ["preserving", "quick"],
  },
  {
    id: "recipe_zucchini_fritters",
    title: "Zucchini Fritters",
    plantIds: ["zucchini"],
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    ingredients: [
      { item: "zucchini, grated and squeezed", quantity: 2, plantId: "zucchini" },
      { item: "egg", quantity: 1 },
      { item: "flour", quantity: 0.5, unit: "cup" },
      { item: "feta, crumbled", quantity: 0.5, unit: "cup" },
      { item: "scallions or chives", quantity: 2 },
    ],
    steps: [
      "Salt grated zucchini, rest 10 minutes, squeeze dry.",
      "Mix with egg, flour, feta, scallions.",
      "Pan-fry spoonfuls until golden on both sides.",
    ],
    usesStage: "harvest",
    tags: ["quick", "vegetarian", "glut-buster"],
  },
  {
    id: "recipe_garlic_green_beans",
    title: "Garlic Green Beans",
    plantIds: ["bush_bean"],
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 10,
    ingredients: [
      { item: "green beans, trimmed", quantity: 400, unit: "g", plantId: "bush_bean" },
      { item: "garlic, sliced", quantity: 3 },
      { item: "olive oil", quantity: 2, unit: "tbsp" },
      { item: "lemon zest", quantity: 1 },
    ],
    steps: [
      "Blanch beans 3 minutes; shock in cold water.",
      "Sizzle garlic in oil, toss beans through, finish with zest.",
    ],
    usesStage: "harvest",
    tags: ["quick", "side"],
  },
  {
    id: "recipe_spring_stir_fry",
    title: "Spring Stir-Fry",
    plantIds: ["snap_pea", "broccoli", "carrot", "pepper_sweet"],
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    ingredients: [
      { item: "snap peas", quantity: 200, unit: "g", plantId: "snap_pea" },
      { item: "broccoli florets", quantity: 1, plantId: "broccoli" },
      { item: "carrots, sliced thin", quantity: 2, plantId: "carrot" },
      { item: "sweet pepper, sliced", quantity: 1, plantId: "pepper_sweet" },
      { item: "soy, ginger, garlic sauce", quantity: 4, unit: "tbsp" },
    ],
    steps: [
      "Stir-fry carrots and broccoli 3 minutes on high heat.",
      "Add peas and pepper for 2 more minutes.",
      "Toss with sauce; serve over rice.",
    ],
    usesStage: "harvest",
    tags: ["quick", "vegetarian"],
  },
  {
    id: "recipe_roasted_broccoli",
    title: "Crispy Roasted Broccoli",
    plantIds: ["broccoli"],
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 20,
    ingredients: [
      { item: "broccoli, in florets", quantity: 1, plantId: "broccoli" },
      { item: "olive oil", quantity: 2, unit: "tbsp" },
      { item: "parmesan", quantity: 0.25, unit: "cup" },
      { item: "lemon", quantity: 0.5 },
    ],
    steps: [
      "Roast oiled florets at 220°C until edges char, ~18 minutes.",
      "Shower with parmesan and lemon.",
    ],
    usesStage: "harvest",
    tags: ["side", "quick"],
  },
  {
    id: "recipe_kale_chips",
    title: "Kale Chips",
    plantIds: ["kale"],
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
    ingredients: [
      { item: "kale leaves, stemmed", quantity: 1, unit: "bunch", plantId: "kale" },
      { item: "olive oil", quantity: 1, unit: "tbsp" },
      { item: "salt", quantity: 0.25, unit: "tsp" },
    ],
    steps: [
      "Massage leaves with oil; spread in one layer.",
      "Bake at 150°C until crisp, 12-15 minutes, watching closely.",
    ],
    usesStage: "harvest",
    tags: ["snack", "quick"],
  },
  {
    id: "recipe_honey_glazed_carrots",
    title: "Honey-Glazed Carrots",
    plantIds: ["carrot"],
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    ingredients: [
      { item: "carrots, halved lengthwise", quantity: 500, unit: "g", plantId: "carrot" },
      { item: "butter", quantity: 2, unit: "tbsp" },
      { item: "honey", quantity: 1, unit: "tbsp" },
      { item: "thyme", quantity: 2, unit: "sprigs" },
    ],
    steps: [
      "Simmer carrots in salted water 8 minutes; drain.",
      "Glaze in butter, honey, and thyme until sticky.",
    ],
    usesStage: "harvest",
    tags: ["side"],
  },
  {
    id: "recipe_quick_pickled_radish",
    title: "Quick-Pickled Radish",
    plantIds: ["radish"],
    servings: 6,
    prepMinutes: 10,
    ingredients: [
      { item: "radishes, sliced thin", quantity: 1, unit: "bunch", plantId: "radish" },
      { item: "rice vinegar", quantity: 0.5, unit: "cup" },
      { item: "sugar", quantity: 1, unit: "tbsp" },
      { item: "salt", quantity: 1, unit: "tsp" },
    ],
    steps: [
      "Dissolve sugar and salt in vinegar.",
      "Pour over radishes; ready in 30 minutes, better next day.",
    ],
    usesStage: "harvest",
    tags: ["preserving", "quick", "taco-topper"],
  },
  {
    id: "recipe_roasted_beets",
    title: "Roasted Beets with Greens",
    plantIds: ["beet"],
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 45,
    ingredients: [
      { item: "beets with tops", quantity: 6, plantId: "beet" },
      { item: "olive oil", quantity: 2, unit: "tbsp" },
      { item: "goat cheese", quantity: 60, unit: "g" },
      { item: "balsamic vinegar", quantity: 1, unit: "tbsp" },
    ],
    steps: [
      "Wrap roots in foil; roast at 200°C until tender, ~40 minutes.",
      "Sauté the greens in oil while beets rest.",
      "Slip skins, slice, plate over greens with cheese and balsamic.",
    ],
    usesStage: "harvest",
    tags: ["side", "whole-plant"],
  },
  {
    id: "recipe_caramelized_onions",
    title: "Slow Caramelized Onions",
    plantIds: ["onion_bulb"],
    servings: 8,
    prepMinutes: 10,
    cookMinutes: 50,
    ingredients: [
      { item: "onions, sliced", quantity: 6, plantId: "onion_bulb" },
      { item: "butter", quantity: 2, unit: "tbsp" },
      { item: "salt", quantity: 0.5, unit: "tsp" },
    ],
    steps: [
      "Cook onions low and slow, stirring every few minutes, 45-50 minutes.",
      "Deglaze with a splash of water as the pan browns.",
      "Freeze in cubes; instant flavor base.",
    ],
    usesStage: "harvest",
    tags: ["batch-cook", "preserving"],
  },
  {
    id: "recipe_garden_salad",
    title: "Everything Garden Salad",
    plantIds: ["lettuce_leaf", "spinach", "radish", "carrot", "cucumber", "kale"],
    servings: 4,
    prepMinutes: 15,
    ingredients: [
      { item: "lettuce, torn", quantity: 4, unit: "cups", plantId: "lettuce_leaf" },
      { item: "young spinach", quantity: 2, unit: "cups", plantId: "spinach" },
      { item: "baby kale, ribboned", quantity: 1, unit: "cup", plantId: "kale" },
      { item: "radishes, sliced", quantity: 4, plantId: "radish" },
      { item: "carrot, shaved", quantity: 1, plantId: "carrot" },
      { item: "cucumber, sliced", quantity: 0.5, plantId: "cucumber" },
      { item: "vinaigrette", quantity: 3, unit: "tbsp" },
    ],
    steps: [
      "Wash and dry the greens well.",
      "Toss everything with vinaigrette just before serving.",
    ],
    usesStage: "harvest",
    tags: ["raw", "quick", "uses-thinnings"],
  },
  {
    id: "recipe_sauteed_spinach",
    title: "Garlic Sautéed Spinach",
    plantIds: ["spinach"],
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 5,
    ingredients: [
      { item: "spinach, washed", quantity: 300, unit: "g", plantId: "spinach" },
      { item: "garlic, sliced", quantity: 2 },
      { item: "olive oil", quantity: 1, unit: "tbsp" },
      { item: "lemon", quantity: 0.25 },
    ],
    steps: [
      "Sizzle garlic in oil; add spinach with water still clinging.",
      "Toss 2 minutes until just wilted; finish with lemon.",
    ],
    usesStage: "harvest",
    tags: ["quick", "side"],
  },
  {
    id: "recipe_pesto",
    title: "Classic Basil Pesto",
    plantIds: ["basil"],
    servings: 6,
    prepMinutes: 15,
    ingredients: [
      { item: "basil leaves, packed", quantity: 2, unit: "cups", plantId: "basil" },
      { item: "pine nuts or walnuts", quantity: 0.33, unit: "cup" },
      { item: "parmesan, grated", quantity: 0.5, unit: "cup" },
      { item: "garlic", quantity: 2 },
      { item: "olive oil", quantity: 0.5, unit: "cup" },
    ],
    steps: [
      "Blitz nuts and garlic; add basil and cheese.",
      "Stream in oil to a loose paste; season.",
      "Freeze flat in bags — summer in February.",
    ],
    usesStage: "vegetative",
    tags: ["preserving", "raw", "batch-cook"],
  },
];
