/** §7.6 — growth stage templates: ordered sequences + typical durations. */

import type { GrowthStageTemplate } from "../types/models";

export const stageTemplates: GrowthStageTemplate[] = [
  {
    id: "tmpl_fruiting_annual",
    appliesTo: "fruiting-annuals",
    sequence: [
      "planted",
      "germination",
      "sprout",
      "seedling",
      "vegetative",
      "flowering",
      "fruiting",
      "harvest",
      "senescence",
    ],
    stageDurations: {
      germination: { min: 5, typical: 7, max: 12 },
      sprout: { min: 5, typical: 7, max: 10 },
      seedling: { min: 10, typical: 14, max: 21 },
      vegetative: { min: 20, typical: 28, max: 40 },
      flowering: { min: 10, typical: 14, max: 21 },
      fruiting: { min: 14, typical: 21, max: 35 },
      harvest: { min: 21, typical: 40, max: 70 },
    },
    stageCareHints: {
      seedling: ["Pot up before roots circle; feed half-strength."],
      vegetative: ["Set supports now — caging later damages roots."],
      flowering: ["Keep moisture even to prevent blossom drop and rot."],
      fruiting: ["Side-dress; water deeply, less often."],
    },
  },
  {
    id: "tmpl_fruiting_vine",
    appliesTo: "cucurbits",
    sequence: [
      "planted",
      "germination",
      "sprout",
      "seedling",
      "vegetative",
      "flowering",
      "fruiting",
      "harvest",
      "senescence",
    ],
    stageDurations: {
      germination: { min: 3, typical: 6, max: 10 },
      sprout: { min: 4, typical: 6, max: 9 },
      seedling: { min: 7, typical: 10, max: 14 },
      vegetative: { min: 14, typical: 21, max: 30 },
      flowering: { min: 7, typical: 10, max: 14 },
      fruiting: { min: 7, typical: 12, max: 21 },
      harvest: { min: 21, typical: 35, max: 60 },
    },
    stageCareHints: {
      flowering: ["First flowers are often male — fruit follows the second flush."],
      harvest: ["Pick young and often to keep vines producing."],
    },
  },
  {
    id: "tmpl_legume",
    appliesTo: "fabaceae",
    sequence: [
      "planted",
      "germination",
      "sprout",
      "seedling",
      "vegetative",
      "flowering",
      "fruiting",
      "harvest",
      "senescence",
    ],
    stageDurations: {
      germination: { min: 6, typical: 9, max: 14 },
      sprout: { min: 4, typical: 6, max: 8 },
      seedling: { min: 7, typical: 10, max: 14 },
      vegetative: { min: 14, typical: 18, max: 28 },
      flowering: { min: 7, typical: 10, max: 14 },
      fruiting: { min: 7, typical: 10, max: 14 },
      harvest: { min: 14, typical: 21, max: 35 },
    },
    stageCareHints: {
      planted: ["Don't pre-soak in cold soil; seeds rot fast."],
      harvest: ["Pick every 2–3 days; mature pods shut down the plant."],
    },
  },
  {
    id: "tmpl_brassica_heading",
    appliesTo: "heading-brassicas",
    sequence: [
      "planted",
      "germination",
      "sprout",
      "seedling",
      "vegetative",
      "budding",
      "harvest",
      "senescence",
    ],
    stageDurations: {
      germination: { min: 4, typical: 7, max: 10 },
      sprout: { min: 4, typical: 6, max: 9 },
      seedling: { min: 10, typical: 14, max: 21 },
      vegetative: { min: 21, typical: 30, max: 45 },
      budding: { min: 10, typical: 14, max: 21 },
      harvest: { min: 7, typical: 14, max: 21 },
    },
    stageCareHints: {
      vegetative: ["Steady nitrogen now builds the frame that sizes the head."],
      budding: ["Watch daily near maturity — heads bolt fast in heat."],
    },
  },
  {
    id: "tmpl_leafy",
    appliesTo: "leafy-greens",
    sequence: [
      "planted",
      "germination",
      "sprout",
      "seedling",
      "vegetative",
      "harvest",
      "senescence",
    ],
    stageDurations: {
      germination: { min: 2, typical: 5, max: 10 },
      sprout: { min: 3, typical: 5, max: 7 },
      seedling: { min: 7, typical: 10, max: 14 },
      vegetative: { min: 10, typical: 16, max: 24 },
      harvest: { min: 14, typical: 28, max: 45 },
    },
    stageCareHints: {
      harvest: ["Cut-and-come-again: take outer leaves, leave the crown."],
    },
  },
  {
    id: "tmpl_root_fast",
    appliesTo: "fast-roots",
    sequence: [
      "planted",
      "germination",
      "sprout",
      "seedling",
      "fruiting",
      "harvest",
      "senescence",
    ],
    stageDurations: {
      germination: { min: 3, typical: 5, max: 7 },
      sprout: { min: 2, typical: 4, max: 6 },
      seedling: { min: 5, typical: 7, max: 10 },
      fruiting: { min: 7, typical: 10, max: 14 },
      harvest: { min: 5, typical: 7, max: 10 },
    },
    stageCareHints: {
      seedling: ["Thin ruthlessly — crowded roots stay pencil-thin."],
      harvest: ["Pull at size; oversized roots turn woody and split."],
    },
  },
  {
    id: "tmpl_root_slow",
    appliesTo: "slow-roots",
    sequence: [
      "planted",
      "germination",
      "sprout",
      "seedling",
      "vegetative",
      "fruiting",
      "harvest",
      "senescence",
    ],
    stageDurations: {
      germination: { min: 6, typical: 14, max: 21 },
      sprout: { min: 4, typical: 7, max: 10 },
      seedling: { min: 10, typical: 14, max: 21 },
      vegetative: { min: 14, typical: 21, max: 30 },
      fruiting: { min: 14, typical: 21, max: 30 },
      harvest: { min: 14, typical: 21, max: 40 },
    },
    stageCareHints: {
      planted: ["Keep the seedbed surface moist — crusting blocks emergence."],
      seedling: ["Thin to final spacing early; carrots never recover from crowding."],
    },
  },
  {
    id: "tmpl_allium_bulb",
    appliesTo: "bulbing-alliums",
    sequence: [
      "planted",
      "germination",
      "sprout",
      "seedling",
      "vegetative",
      "fruiting",
      "harvest",
      "senescence",
    ],
    stageDurations: {
      germination: { min: 7, typical: 10, max: 14 },
      sprout: { min: 5, typical: 7, max: 10 },
      seedling: { min: 14, typical: 21, max: 28 },
      vegetative: { min: 30, typical: 45, max: 60 },
      fruiting: { min: 21, typical: 30, max: 45 },
      harvest: { min: 7, typical: 14, max: 21 },
    },
    stageCareHints: {
      vegetative: ["Every leaf is a future bulb ring — feed and weed now."],
      fruiting: ["Stop watering once tops begin to fall; let bulbs cure dry."],
    },
  },
  {
    id: "tmpl_herb_leafy",
    appliesTo: "leafy-herbs",
    sequence: [
      "planted",
      "germination",
      "sprout",
      "seedling",
      "vegetative",
      "flowering",
      "senescence",
    ],
    stageDurations: {
      germination: { min: 5, typical: 8, max: 14 },
      sprout: { min: 4, typical: 6, max: 9 },
      seedling: { min: 10, typical: 14, max: 21 },
      vegetative: { min: 21, typical: 40, max: 70 },
      flowering: { min: 14, typical: 21, max: 30 },
    },
    stageCareHints: {
      vegetative: ["Pinch growing tips constantly; harvest IS the pruning."],
      flowering: ["Flavor fades at bloom — pinch buds to extend the leaf run."],
    },
  },
];
