/** §7.4 — varietals. DTM overrides the parent plant where present. */

import type { Varietal } from "../types/models";

export const varietals: Varietal[] = [
  // --- tomato ---
  {
    id: "tomato_sungold",
    plantId: "tomato",
    name: "Sungold",
    description: "Orange cherry, famously sweet, first to ripen and last to quit.",
    daysToMaturity: { min: 55, max: 65 },
    traits: ["cherry", "indeterminate", "crack-prone", "very sweet"],
    colorHex: "#f5a623",
    flavorNotes: "Tropical-sweet, low acid.",
    bestFor: ["fresh eating", "containers", "short-season"],
  },
  {
    id: "tomato_san_marzano",
    plantId: "tomato",
    name: "San Marzano",
    description: "The classic paste tomato: dense flesh, few seeds.",
    daysToMaturity: { min: 78, max: 90 },
    traits: ["paste", "indeterminate", "meaty"],
    colorHex: "#d23c2e",
    flavorNotes: "Rich and low-moisture; built for sauce.",
    bestFor: ["sauce", "canning"],
  },
  {
    id: "tomato_early_girl",
    plantId: "tomato",
    name: "Early Girl",
    description: "Reliable early slicer for short or cool seasons.",
    daysToMaturity: { min: 57, max: 63 },
    traits: ["slicer", "indeterminate", "early", "disease-resistant VF"],
    colorHex: "#c93c2e",
    flavorNotes: "Balanced, classic tomato.",
    bestFor: ["short-season", "fresh eating"],
  },
  // --- pepper ---
  {
    id: "pepper_california_wonder",
    plantId: "pepper_sweet",
    name: "California Wonder",
    description: "The standard blocky bell; green to red.",
    daysToMaturity: { min: 65, max: 75 },
    traits: ["bell", "thick-walled"],
    colorHex: "#d23c2e",
    bestFor: ["stuffing", "fresh eating"],
  },
  {
    id: "pepper_banana",
    plantId: "pepper_sweet",
    name: "Sweet Banana",
    description: "Long pale-yellow fruit, early and prolific in cooler summers.",
    daysToMaturity: { min: 60, max: 70 },
    traits: ["early", "prolific", "tapered"],
    colorHex: "#e8c84a",
    bestFor: ["short-season", "pickling", "frying"],
  },
  // --- cucumber ---
  {
    id: "cucumber_marketmore",
    plantId: "cucumber",
    name: "Marketmore 76",
    description: "Dependable dark-green slicer with broad disease resistance.",
    daysToMaturity: { min: 58, max: 68 },
    traits: ["slicer", "disease-resistant", "open-pollinated"],
    bestFor: ["fresh eating", "reliability"],
  },
  {
    id: "cucumber_lemon",
    plantId: "cucumber",
    name: "Lemon",
    description: "Round yellow heirloom; thin-skinned, mild, never bitter.",
    daysToMaturity: { min: 60, max: 70 },
    traits: ["heirloom", "round", "mild"],
    colorHex: "#e8d44a",
    bestFor: ["fresh eating", "novelty"],
  },
  // --- zucchini ---
  {
    id: "zucchini_black_beauty",
    plantId: "zucchini",
    name: "Black Beauty",
    description: "Glossy deep-green standard; open habit eases picking.",
    daysToMaturity: { min: 45, max: 55 },
    traits: ["heirloom", "prolific"],
    bestFor: ["reliability", "freezing"],
  },
  // --- beans/peas ---
  {
    id: "bean_provider",
    plantId: "bush_bean",
    name: "Provider",
    description: "Earliest dependable bush bean; germinates in cooler soil than most.",
    daysToMaturity: { min: 48, max: 55 },
    traits: ["early", "cool-soil tolerant", "heavy set"],
    bestFor: ["short-season", "first sowing"],
  },
  {
    id: "bean_royal_burgundy",
    plantId: "bush_bean",
    name: "Royal Burgundy",
    description: "Purple pods (easy to spot), turn green when cooked.",
    daysToMaturity: { min: 55, max: 60 },
    traits: ["purple", "easy-pick", "cool-soil tolerant"],
    colorHex: "#6a2c5f",
    bestFor: ["kids", "fresh eating"],
  },
  {
    id: "pea_sugar_snap",
    plantId: "snap_pea",
    name: "Sugar Snap",
    description: "The original tall snap pea; needs a real trellis.",
    daysToMaturity: { min: 62, max: 70 },
    traits: ["tall 180cm", "sweet", "heavy yield"],
    bestFor: ["flavor", "trellised beds"],
  },
  {
    id: "pea_cascadia",
    plantId: "snap_pea",
    name: "Cascadia",
    description: "Compact snap pea bred in the Northwest; mildew-resistant.",
    daysToMaturity: { min: 58, max: 65 },
    traits: ["dwarf 80cm", "disease-resistant", "PNW-bred"],
    bestFor: ["containers", "small trellis", "damp climates"],
  },
  // --- brassicas ---
  {
    id: "broccoli_calabrese",
    plantId: "broccoli",
    name: "Calabrese",
    description: "Italian heirloom; medium head then weeks of side shoots.",
    daysToMaturity: { min: 60, max: 75 },
    traits: ["heirloom", "side shoots"],
    bestFor: ["long harvest"],
  },
  {
    id: "broccoli_belstar",
    plantId: "broccoli",
    name: "Belstar",
    description: "Uniform hybrid that holds in heat better than most.",
    daysToMaturity: { min: 55, max: 66 },
    traits: ["hybrid", "heat-tolerant", "uniform"],
    bestFor: ["spring and fall", "reliability"],
  },
  {
    id: "kale_lacinato",
    plantId: "kale",
    name: "Lacinato (Dinosaur)",
    description: "Dark strap leaves, Tuscan classic; sweetest after frost.",
    daysToMaturity: { min: 55, max: 65 },
    traits: ["heirloom", "tender-leaved"],
    colorHex: "#2a5c44",
    bestFor: ["cooking", "salads when young"],
  },
  {
    id: "kale_red_russian",
    plantId: "kale",
    name: "Red Russian",
    description: "Purple-veined, flat-leaved, extremely cold-hardy.",
    daysToMaturity: { min: 50, max: 60 },
    traits: ["very hardy", "tender"],
    colorHex: "#7a4f6a",
    bestFor: ["overwintering", "salads"],
  },
  // --- roots ---
  {
    id: "carrot_nantes",
    plantId: "carrot",
    name: "Nantes",
    description: "Blunt-tipped, crisp and sweet; the home-garden standard.",
    daysToMaturity: { min: 62, max: 70 },
    traits: ["cylindrical", "sweet", "crisp"],
    bestFor: ["fresh eating", "heavier soils"],
  },
  {
    id: "carrot_danvers",
    plantId: "carrot",
    name: "Danvers 126",
    description: "Tapered storage carrot that handles heavier soil.",
    daysToMaturity: { min: 70, max: 80 },
    traits: ["storage", "vigorous tops"],
    bestFor: ["storage", "clay-ish soils"],
  },
  {
    id: "carrot_rainbow",
    plantId: "carrot",
    name: "Rainbow Mix",
    description: "Purple, yellow, white, and orange roots in one sowing.",
    daysToMaturity: { min: 65, max: 75 },
    traits: ["multicolor", "mix"],
    colorHex: "#b06ad2",
    bestFor: ["kids", "market bunches"],
  },
  {
    id: "radish_cherry_belle",
    plantId: "radish",
    name: "Cherry Belle",
    description: "Round red 22-day classic; the speed benchmark.",
    daysToMaturity: { min: 22, max: 26 },
    traits: ["round", "mild", "fast"],
    bestFor: ["first crop", "kids"],
  },
  {
    id: "radish_french_breakfast",
    plantId: "radish",
    name: "French Breakfast",
    description: "Oblong, red with a white tip; mild and elegant.",
    daysToMaturity: { min: 25, max: 30 },
    traits: ["oblong", "heirloom", "mild"],
    bestFor: ["fresh eating"],
  },
  {
    id: "beet_detroit_dark_red",
    plantId: "beet",
    name: "Detroit Dark Red",
    description: "Round, deep-red standard for roots and greens alike.",
    daysToMaturity: { min: 55, max: 65 },
    traits: ["heirloom", "storage"],
    bestFor: ["all-purpose", "canning"],
  },
  {
    id: "beet_chioggia",
    plantId: "beet",
    name: "Chioggia",
    description: "Candy-striped Italian heirloom, mild and early.",
    daysToMaturity: { min: 50, max: 60 },
    traits: ["heirloom", "striped", "mild"],
    colorHex: "#d2688a",
    bestFor: ["fresh eating", "roasting"],
  },
  // --- onion ---
  {
    id: "onion_walla_walla",
    plantId: "onion_bulb",
    name: "Walla Walla",
    description: "Famous sweet long-day onion for the Northwest; eat fresh, doesn't store.",
    daysToMaturity: { min: 90, max: 110 },
    traits: ["long-day", "sweet", "poor storage"],
    bestFor: ["fresh eating", "northern latitudes"],
  },
  {
    id: "onion_red_baron",
    plantId: "onion_bulb",
    name: "Red Baron",
    description: "Deep-red long-day storage onion.",
    daysToMaturity: { min: 100, max: 115 },
    traits: ["long-day", "storage", "red"],
    colorHex: "#8c2f4f",
    bestFor: ["storage", "salads"],
  },
  // --- leafy ---
  {
    id: "lettuce_black_seeded_simpson",
    plantId: "lettuce_leaf",
    name: "Black Seeded Simpson",
    description: "Fast, frilly, lime-green heirloom; the cut-and-come-again standard.",
    daysToMaturity: { min: 28, max: 45 },
    traits: ["heirloom", "fast", "loose-leaf"],
    bestFor: ["first sowing", "succession"],
  },
  {
    id: "lettuce_oakleaf",
    plantId: "lettuce_leaf",
    name: "Oakleaf",
    description: "Lobed tender leaves; slower to bolt than most.",
    daysToMaturity: { min: 30, max: 50 },
    traits: ["bolt-resistant", "tender"],
    bestFor: ["warm spells", "salad mixes"],
  },
  {
    id: "spinach_bloomsdale",
    plantId: "spinach",
    name: "Bloomsdale Long Standing",
    description: "Savoyed heirloom that stands longer before bolting.",
    daysToMaturity: { min: 40, max: 50 },
    traits: ["heirloom", "savoyed", "bolt-resistant"],
    bestFor: ["spring", "flavor"],
  },
  {
    id: "spinach_space",
    plantId: "spinach",
    name: "Space",
    description: "Smooth-leaf hybrid, quick and mildew-resistant.",
    daysToMaturity: { min: 35, max: 45 },
    traits: ["hybrid", "smooth-leaf", "disease-resistant"],
    bestFor: ["fall", "damp climates"],
  },
  // --- basil ---
  {
    id: "basil_genovese",
    plantId: "basil",
    name: "Genovese",
    description: "The pesto basil: big tender leaves, classic aroma.",
    traits: ["large-leaf", "classic"],
    bestFor: ["pesto", "caprese"],
  },
  {
    id: "basil_thai",
    plantId: "basil",
    name: "Thai",
    description: "Anise-scented, purple-stemmed; holds flavor when cooked.",
    traits: ["anise-scented", "heat-stable flavor"],
    colorHex: "#6a2c5f",
    bestFor: ["stir-fries", "curries"],
  },
];
